#!/usr/bin/python3
def raise_exception():
    a = 2
    b = 'three'
    return a + b
    